# Array Indexing: Accessing Single Elements
### If you are familiar with Python's standard list indexing, indexing in NumPy will feel quite familiar. In a one-dimensional array, the $i^{th}$ value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [9]:
import numpy as np
np.random.seed(0)

In [10]:
x1 = np.random.randint(8, size=(3, 5))

In [11]:
print("x1 ndim: ", x1.ndim)
print("x1 shape:", x1.shape)
print("x1 size: ", x1.size)

x1 ndim:  2
x1 shape: (3, 5)
x1 size:  15


In [12]:
print("dtype:", x1.dtype)

dtype: int32


In [13]:
print("itemsize:", x1.itemsize, "bytes")
print("nbytes:", x1.nbytes, "bytes")

itemsize: 4 bytes
nbytes: 60 bytes


# NUOVO

In [14]:
x1

array([[4, 7, 5, 0, 3],
       [3, 3, 7, 1, 3],
       [5, 2, 4, 7, 6]])

In [15]:
x1[0]
x1[0] = x1[0]+10
x1[0]

array([14, 17, 15, 10, 13])

In [19]:
x1

array([[14, 17, 15, 10, 13],
       [ 3,  3,  7,  1,  3],
       [ 5,  2,  4,  7,  6]])

To index from the end of the array, you can use negative indices:

In [20]:
x1[-1]

array([5, 2, 4, 7, 6])

In [21]:
x1[-2]

array([3, 3, 7, 1, 3])

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [23]:
x2 = np.random.randint(10, size=(3, 4)) 

In [24]:
x2

array([[8, 8, 1, 6],
       [7, 7, 8, 1],
       [5, 9, 8, 9]])

In [25]:
x2[2, 0]

5

Values can also be modified using any of the above index notation:

In [26]:
x2[0, 0] = 12
x2

array([[12,  8,  1,  6],
       [ 7,  7,  8,  1],
       [ 5,  9,  8,  9]])

Keep in mind that, unlike Python lists, NumPy arrays have a fixed type. This means, for example, that if you attempt to insert a floating-point value to an integer array, the value will be silently truncated. Don't be caught unaware by this behavior!


In [29]:
x1[0] = 3.14159 
x1

array([[3, 3, 3, 3, 3],
       [3, 3, 7, 1, 3],
       [5, 2, 4, 7, 6]])

In [28]:
# this .14159 will be truncated!

# ES. 1

In [65]:
import numpy as np
np.random.seed(0)

In [66]:
es1= np.random.randint(8, size=(5, 3))

In [67]:
es1 [0,2]

5

In [69]:
es1[3,-1]

2

In [70]:
print(es1[3,2]+7)

9


In [76]:
a= es1[0,0]+es1[1,0]

In [77]:
es1[2,0]=a

In [80]:
print(es1[2,0])

4
