# Creating Arrays from Python Lists
First, we can use np.array to create arrays from Python lists:

# integer array:


In [6]:
import numpy as np
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

Remember that unlike Python lists, NumPy is constrained to arrays that all contain the same type. If types do not match, NumPy will upcast if possible (here, integers are up-cast to floating point):


In [7]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

If we want to explicitly set the data type of the resulting array, we can use the dtype keyword:

In [8]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

Finally, unlike Python lists, NumPy arrays can explicitly be multi-dimensional; here's one way of initializing a multidimensional array using a list of lists:


In [9]:
np.array([range(i, i + 3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

The inner lists are treated as rows of the resulting two-dimensional array.

Creating Arrays from Scratch
Especially for larger arrays, it is more efficient to create arrays from scratch using routines built into NumPy. Here are several examples:


# Create a length-50 integer array filled with zeros

In [51]:
np.zeros(50, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0])

# Create a 2x5 floating-point array filled with ones

In [52]:
np.ones((5, 2), dtype=float)

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])


# Create a 3x3 array filled with 12.34

In [53]:
np.full((3, 3), 12.34)

array([[12.34, 12.34, 12.34],
       [12.34, 12.34, 12.34],
       [12.34, 12.34, 12.34]])


# Create an array filled with a linear sequence
# Starting at 6, ending at 46, stepping by 4
# (this is similar to the built-in range() function)

In [54]:
np.arange(6, 46, 4)

array([ 6, 10, 14, 18, 22, 26, 30, 34, 38, 42])

# Create an array of fifteen values evenly spaced between 0 and 100, stepping by 5

In [55]:
np.linspace(0, 100, 20, dtype= float)

array([  0.        ,   5.26315789,  10.52631579,  15.78947368,
        21.05263158,  26.31578947,  31.57894737,  36.84210526,
        42.10526316,  47.36842105,  52.63157895,  57.89473684,
        63.15789474,  68.42105263,  73.68421053,  78.94736842,
        84.21052632,  89.47368421,  94.73684211, 100.        ])


# Create a 1x10 array of uniformly distributed
# random values between 0 and 1

In [56]:
np.random.random((10, 1))

array([[0.38096556],
       [0.96843877],
       [0.17284901],
       [0.39582858],
       [0.16028657],
       [0.46793627],
       [0.53356515],
       [0.87389829],
       [0.95585592],
       [0.58742983]])

# Create a 2x10 array of normally distributed random values
# with mean 0 and standard deviation 1

In [57]:
np.random.normal(0, 1, (10, 2))

array([[ 1.19407744,  1.25254556],
       [ 0.56503169,  0.86007612],
       [ 0.85186149,  0.00464215],
       [-0.88445106,  0.06766699],
       [-0.07716651, -0.22924438],
       [-0.51533843,  0.03400628],
       [ 0.53369148, -0.1047153 ],
       [ 0.36424743,  0.53133899],
       [-1.12179534,  1.51720295],
       [ 1.01904037,  0.90098681]])

# Create a 3x3 array of random integers in the interval (0, 10)

In [58]:
np.random.randint(0, 10, (3, 3))

array([[0, 6, 9],
       [5, 9, 5],
       [0, 8, 8]])

# Create a 3x3 identity matrix

In [59]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location

In [60]:
np.empty(3)

array([1., 1., 1.])